'use server'

import { prisma } from '@/lib/db'
import { revalidatePath } from 'next/cache'

const BASE_URL = process.env.NEXT_PUBLIC_BASE_URL || 'http://127.0.0.1:3005'
const WEBHOOK_SECRET = process.env.WEBHOOK_SECRET || 'your-secret-key'

// 1. Contact Form Test
export async function runContactTest() {
    try {
        const res = await fetch(`${BASE_URL}/api/contact`, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({
                name: 'System Test',
                email: 'test@system.local',
                subject: '[SYSTEM TEST] verification',
                message: 'This is a test message from the System Health Check.'
            })
        })

        if (!res.ok) throw new Error(`API Error: ${res.status}`)

        // Verify DB
        const submission = await prisma.contactSubmission.findFirst({
            where: { email: 'test@system.local' },
            orderBy: { createdAt: 'desc' }
        })

        if (!submission) throw new Error('Submission not found in DB')

        return { success: true, message: `Created submission ID: ${submission.id}` }
    } catch (e: any) {
        return { success: false, error: e.message }
    }
}

// 2. Article Create Test
export async function runArticleCreateTest() {
    try {
        const article = await prisma.article.create({
            data: {
                status: 'published',
                publishedAt: new Date(),
                translations: {
                    create: {
                        locale: 'en',
                        slug: 'system-test-article-' + Date.now(),
                        title: '[SYSTEM TEST] Auto Generated Article',
                        contentHtml: '<p>This is a test article generated by the system health check.</p>',
                        metaTitle: 'Test Article',
                        metaDescription: 'Test Description'
                    }
                }
            }
        })
        return { success: true, message: `Created Article ID: ${article.id}` }
    } catch (e: any) {
        return { success: false, error: e.message }
    }
}

// 3. View Analytics Test
export async function runViewTest() {
    try {
        // Find the test article or any article
        const article = await prisma.article.findFirst({
            where: { translations: { some: { title: { contains: '[SYSTEM TEST]' } } } }
        })

        if (!article) throw new Error('No test article found to view. Run Article Test first.')

        await prisma.articleView.create({
            data: { articleId: article.id }
        })

        return { success: true, message: `Logged view for Article ID: ${article.id}` }
    } catch (e: any) {
        return { success: false, error: e.message }
    }
}

// 4. Webhook Success Test
export async function runWebhookSuccessTest() {
    try {
        const payload = {
            secret: WEBHOOK_SECRET,
            action: 'create',
            data: {
                slug: 'webhook-test-' + Date.now(),
                locale: 'en',
                title: '[SYSTEM TEST] Webhook Article',
                contentHtml: '<p>Created via Webhook Test</p>',
                metaTitle: 'Webhook Test',
                status: 'published',
                publishedAt: new Date().toISOString()
            }
        }

        const res = await fetch(`${BASE_URL}/api/webhooks/content`, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify(payload)
        })

        if (!res.ok) throw new Error(`Webhook API Error: ${res.status}`)

        return { success: true, message: 'Webhook sent successfully (200 OK)' }
    } catch (e: any) {
        return { success: false, error: e.message }
    }
}

// 5. Webhook Error Test
export async function runWebhookErrorTest() {
    try {
        const payload = {
            secret: WEBHOOK_SECRET,
            action: 'error',
            data: {
                error: 'Simulated Error from System Test',
                details: { reason: 'Testing error reporting flow' },
                slug: 'failed-generation-test'
            }
        }

        const res = await fetch(`${BASE_URL}/api/webhooks/content`, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify(payload)
        })

        // The API returns 200 even for error reports (it logged it successfully)
        if (!res.ok) throw new Error(`Webhook API Failed: ${res.status}`)

        return { success: true, message: 'Error Report sent successfully' }
    } catch (e: any) {
        return { success: false, error: e.message }
    }
}
